# Generated by Django 3.2.7 on 2021-10-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='user_profiles',
        ),
    ]
