# Generated by Django 3.2.7 on 2021-10-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('employee', 'employee'), ('client', 'client')], max_length=50),
        ),
    ]
