# Generated by Django 3.2.7 on 2021-10-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notify_sent',
            field=models.BooleanField(default=0),
        ),
    ]
